In [ ]:
import requests

url = "https://api.coinpaprika.com/v1/tickers/{coin_id}?quotes=USD"

coins_id= {'btc-bitcoin','eth-ethereum','trx-tron'}

coin_data = []


##url.format here is used to treat placeholders in url
for coin in coins_id:
    response = requests.get(url.format(coin_id = coin))
    response.raise_for_status()
    coin_data.append(response.json())

In [17]:
##The first step in transformation is picking the useful data

## The pd.json_normalized command is very useful especially in instances where you have dictionaries inside other dictionaries


##Looking at the normalized columns you can tell that the data has been flattened out into header and data instead of sub dictionaries


##this way, one can have same output for multiple coins withour feeling overwhelmed by the screen output

In [18]:
## Next step is to normalize data for the three coins that we have
import pandas as pd

coins_df = pd.json_normalize(coin_data)
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,first_data_at,last_updated,quotes.USD.price,...,quotes.USD.percent_change_1h,quotes.USD.percent_change_6h,quotes.USD.percent_change_12h,quotes.USD.percent_change_24h,quotes.USD.percent_change_7d,quotes.USD.percent_change_30d,quotes.USD.percent_change_1y,quotes.USD.ath_price,quotes.USD.ath_date,quotes.USD.percent_from_price_ath
0,trx-tron,TRON,TRX,8,94892743836,0,0.300580,2017-09-13T00:00:00Z,2026-08-06T02:40:15Z,0.328017,...,-0.08,0.09,0.09,0.48,0.82,0,0,0.440441,2024-12-04T00:12:23Z,-25.52
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.434560,2015-08-07T00:00:00Z,2026-08-06T02:43:15Z,1897.346801,...,-0.50,-1.00,1.14,1.71,-0.55,0,0,4946.229670,2025-08-24T19:24:38Z,-61.68
2,btc-bitcoin,Bitcoin,BTC,1,20066359,21000000,0.993427,2010-07-17T00:00:00Z,2026-08-06T02:39:15Z,64446.594000,...,-0.18,-0.61,0.16,0.56,0.59,0,0,126173.177785,2025-10-06T19:00:40Z,-48.89

In [19]:
## The next step is dropping the columns you dont require

coins_df.drop(columns=['first_data_at','quotes.USD.percent_change_1h', 'quotes.USD.percent_change_30m', 'quotes.USD.percent_change_6h', 
                       'quotes.USD.percent_change_12h'], inplace= True)

In [20]:
## Drop a few other columns
coins_df.columns

Index(['id', 'name', 'symbol', 'rank', 'total_supply', 'max_supply',
       'beta_value', 'last_updated', 'quotes.USD.price',
       'quotes.USD.volume_24h', 'quotes.USD.volume_24h_change_24h',
       'quotes.USD.market_cap', 'quotes.USD.market_cap_change_24h',
       'quotes.USD.percent_change_15m', 'quotes.USD.percent_change_24h',
       'quotes.USD.percent_change_7d', 'quotes.USD.percent_change_30d',
       'quotes.USD.percent_change_1y', 'quotes.USD.ath_price',
       'quotes.USD.ath_date', 'quotes.USD.percent_from_price_ath'],
      dtype='str')

In [21]:
coins_df.drop(columns=['quotes.USD.percent_change_7d',
                       'quotes.USD.percent_change_1y',
                       'quotes.USD.percent_change_24h',
                       'quotes.USD.percent_change_30d',
                       'quotes.USD.percent_change_15m'], inplace = True)

In [22]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,quotes.USD.price,quotes.USD.volume_24h,quotes.USD.volume_24h_change_24h,quotes.USD.market_cap,quotes.USD.market_cap_change_24h,quotes.USD.ath_price,quotes.USD.ath_date,quotes.USD.percent_from_price_ath
0,trx-tron,TRON,TRX,8,94892743836,0,0.300580,2026-08-06T02:40:15Z,0.328017,3.567896e+08,-15.600000,31126466609,0.48,0.440441,2024-12-04T00:12:23Z,-25.52
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.434560,2026-08-06T02:43:15Z,1897.346801,7.132308e+09,26.690001,228490485413,1.71,4946.229670,2025-08-24T19:24:38Z,-61.68
2,btc-bitcoin,Bitcoin,BTC,1,20066359,21000000,0.993427,2026-08-06T02:39:15Z,64446.594000,1.857105e+10,-5.000000,1293208491535,0.56,126173.177785,2025-10-06T19:00:40Z,-48.89

In [23]:
coins_df.columns

Index(['id', 'name', 'symbol', 'rank', 'total_supply', 'max_supply',
       'beta_value', 'last_updated', 'quotes.USD.price',
       'quotes.USD.volume_24h', 'quotes.USD.volume_24h_change_24h',
       'quotes.USD.market_cap', 'quotes.USD.market_cap_change_24h',
       'quotes.USD.ath_price', 'quotes.USD.ath_date',
       'quotes.USD.percent_from_price_ath'],
      dtype='str')

In [24]:
coins_df.rename(columns={'quotes.USD.price':'price_USD', 
                         'quotes.USD.volume_24h':'volume_in_24h',
                         'quotes.USD.volume_24h_change_24h':'volume_change_in_24h',
                         'quotes.USD.market_cap':'mkt_cap',
                         'quotes.USD.market_cap_change_24h':'mkt_cap_change',
                         'quotes.USD.ath_price':'ath_price', 
                         'quotes.USD.ath_date':'ath_date',
                         'quotes.USD.percent_from_price_ath':'%_from_price_ath'
                        }, inplace=True
                )

In [25]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,price_USD,volume_in_24h,volume_change_in_24h,mkt_cap,mkt_cap_change,ath_price,ath_date,%_from_price_ath
0,trx-tron,TRON,TRX,8,94892743836,0,0.300580,2026-08-06T02:40:15Z,0.328017,3.567896e+08,-15.600000,31126466609,0.48,0.440441,2024-12-04T00:12:23Z,-25.52
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.434560,2026-08-06T02:43:15Z,1897.346801,7.132308e+09,26.690001,228490485413,1.71,4946.229670,2025-08-24T19:24:38Z,-61.68
2,btc-bitcoin,Bitcoin,BTC,1,20066359,21000000,0.993427,2026-08-06T02:39:15Z,64446.594000,1.857105e+10,-5.000000,1293208491535,0.56,126173.177785,2025-10-06T19:00:40Z,-48.89

In [26]:
## Changing a string to a timestamp

coins_df['last_updated'] = pd.to_datetime(coins_df['last_updated'])

In [27]:
## the final process in transformation is getting a timestamp from last updated
import datetime

coins_df['time_last_updated'] = coins_df['last_updated'].dt.time

In [28]:
coins_df.head()

,id,name,symbol,rank,total_supply,max_supply,beta_value,last_updated,price_USD,volume_in_24h,volume_change_in_24h,mkt_cap,mkt_cap_change,ath_price,ath_date,%_from_price_ath,time_last_updated
0,trx-tron,TRON,TRX,8,94892743836,0,0.300580,2026-08-06 02:40:15+00:00,0.328017,3.567896e+08,-15.600000,31126466609,0.48,0.440441,2024-12-04T00:12:23Z,-25.52,02:40:15
1,eth-ethereum,Ethereum,ETH,2,120232214,0,1.434560,2026-08-06 02:43:15+00:00,1897.346801,7.132308e+09,26.690001,228490485413,1.71,4946.229670,2025-08-24T19:24:38Z,-61.68,02:43:15
2,btc-bitcoin,Bitcoin,BTC,1,20066359,21000000,0.993427,2026-08-06 02:39:15+00:00,64446.594000,1.857105e+10,-5.000000,1293208491535,0.56,126173.177785,2025-10-06T19:00:40Z,-48.89,02:39:15

In [ ]:
## The next step is the loading where we get to load the extracted data from the website

import os
from dotenv import load_dotenv

##This command enables us to read from .env file
load_dotenv(override=True)
## The override = True enables you to update the variables in the environment without relying on cached values

DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_PASSWORD =os.getenv('DATABASE_PASSWORD')
DATABASE_PORT= os.getenv('DATABASE_PORT')

In [32]:
## When you want to pip install psycopg2 you ussually install psycopg2-binary
import psycopg2
from sqlalchemy import create_engine,text

## Create the engine
engine = create_engine(f'postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}')

In [35]:
##The command here creates a table 'coins' in the db name stated in the env and if the table exists,

## It appends new records

coins_df.to_sql('coins',engine, if_exists='append', index=False)

3

In [36]:
## Lets see if we can fetch the data from the database

with engine.connect() as conn:
    result = conn.execute(text('select * from coins;'))
    for line in result:
        print(line)

('trx-tron', 'TRON', 'TRX', 8, 94892743836, 0, 0.30058, datetime.datetime(2026, 8, 6, 5, 40, 15, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800))), 0.3280173156369776, 356789619.33322793, -15.600000381469727, 31126466609, 0.47999998927116394, 0.4404408234447792, '2024-12-04T00:12:23Z', -25.52, datetime.time(2, 40, 15))
('eth-ethereum', 'Ethereum', 'ETH', 2, 120232214, 0, 1.43456, datetime.datetime(2026, 8, 6, 5, 43, 15, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800))), 1897.3468009578778, 7132307921.921248, 26.690000534057617, 228490485413, 1.7100000381469727, 4946.229669645212, '2025-08-24T19:24:38Z', -61.68, datetime.time(2, 43, 15))
('btc-bitcoin', 'Bitcoin', 'BTC', 1, 20066359, 21000000, 0.993427, datetime.datetime(2026, 8, 6, 5, 39, 15, tzinfo=datetime.timezone(datetime.timedelta(seconds=10800))), 64446.59400020031, 18571054820.492775, -5.0, 1293208491535, 0.5600000023841858, 126173.1777846797, '2025-10-06T19:00:40Z', -48.89, datetime.time(2, 39, 15))

In [37]:
## The data has been successfully loaded onto the database
## The next step after this will be to modularize